import { bigint, pgTable, timestamp, uuid, text, boolean, integer, unique } from "drizzle-orm/pg-core";

// ─── repositories ─────────────────────────────────────────────────────────────
// One row per GitHub repository that has installed the GitHub App.
// This is the root configuration object for the entire system.
export const repositories = pgTable("repositories", {
  id: uuid().primaryKey().defaultRandom(), // This is the unique id, it is generated by the database
  githubRepoId: bigint({ mode: "number" }).notNull().unique(), // This is the id of the repository on GitHub
  owner: text().notNull(), // This is the owner/user of the repository
  name: text().notNull(), // This is the name of the repository
  installationId: bigint({ mode: "number" }).notNull(), // This is the id of the installation on GitHub (used for generating the auth token),
  is_active: boolean().notNull().default(true), // This is the active status of the repository,
  
  createdAt: timestamp().notNull().defaultNow(),
  updatedAt: timestamp().notNull().defaultNow(),
});

// ─── webhook_events ───────────────────────────────────────────────────────────
// Append-only log of every webhook delivery received.
// This table has two jobs: idempotency enforcement and debugging/replay.
export const webhookEvents = pgTable("webhook_events", {
  id: uuid().primaryKey().defaultRandom(), // This is the unique id, it is generated by the database
  deliveryId: text().notNull().unique(), // This is the delivery id of the webhook event (used for idempotency enforcement) X-GitHub-Delivery header sent by Github webhooks
  event: text().notNull(), // This is the X-Github-Event header sent by Github webhooks (e.g. "push", "pull_request", "issue_comment", etc.)
  action: text(), // This is the action that was performed (e.g. "opened", "closed", "merged", etc.)
  repositoryId: uuid().references(() => repositories.id, { onDelete: "cascade" }), // This is the id of the repository that the webhook event belongs to
  processedAt: timestamp(), // This is the timestamp when the job is successfully enqueued for processing
  createdAt: timestamp().notNull().defaultNow(),
});

// ─── pull_requests ────────────────────────────────────────────────────────────
// One row per PR, across its entire open lifetime.
// A PR can generate multiple reviews (one per commit push).
// This row ties all those reviews together.
export const pullRequests = pgTable("pull_requests", {
  id: uuid().primaryKey().defaultRandom(), // This is the unique id, it is generated by the database
  repositoryId: uuid().references(() => repositories.id, { onDelete: "cascade" }).notNull(), // This is the id of the repository that the pull request belongs to
  github_pr_id: bigint({ mode: "number" }).notNull(), // This is the id of the pull request on GitHub 
  pr_number: integer().notNull(), // This is the number of the pull request (#124, #125, etc.)
  title: text().notNull(), // This is the title of the pull request (Sent to Groq to have some initial context)
  authorLogin: text().notNull(), // This is the login of the author of the pull request
  base_branch: text().notNull(), // This is the base branch of the pull request ("main", "master", etc.)
  head_branch: text().notNull(), // This is the head branch of the pull request ("feature/123", "bug/124", etc.)
  head_sha: text().notNull(), // the SHA of the latest commit on the head branch at that moment
  state: text().notNull(), // This is the state of the pull request (open, closed, etc.)
  createdAt: timestamp().notNull().defaultNow(),
  updatedAt: timestamp().notNull().defaultNow(),
}, (t) => ([
  unique('github_pr_id_unique').on(t.repositoryId, t.github_pr_id),
]));

// ─── reviews ──────────────────────────────────────────────────────────────────
// One row per analysis run. A PR has many reviews over its lifetime
// (one per commit push that triggers the webhook).
export const reviews = pgTable("reviews", {
  id: uuid().primaryKey().defaultRandom(), // This is the unique id, it is generated by the database
  pull_request_id: uuid().references(() => pullRequests.id, { onDelete: "cascade" }).notNull(), // This is the id of the pull request that the review belongs to
  head_sha: text().notNull(),
  status: text().notNull().default('pending'), // Status of the review ("pending", "processing", "completed", etc.)
  triggered_by: text().notNull(), // Triggered by ("opened", "synchronized", "manual", etc.)
  github_review_id: bigint({ mode: 'number' }), // The id assigned by Github after posting the review via API
  summary: text(),
  files_analyzed: integer().default(0),
  duration_ms: integer(),
  error_message: text(),
  created_at: timestamp().notNull().defaultNow(),
  started_at: timestamp(),
  completed_at: timestamp()
});

// ─── review_comments ──────────────────────────────────────────────────────────
// One row per inline comment posted to a specific line in the diff.
// A review has many comments.
export const review_comments = pgTable("review_comments", {
    id: uuid().primaryKey().defaultRandom(), // This is the unique id, it is generated by the database
    review_id: uuid().references(() => reviews.id, { onDelete: "cascade" }).notNull(),
    file_path: text().notNull(), // The path of the file this comment is on, relative to repo root
    line: integer().notNull(), // Used for inline comments (where to put the inline comment on)
    side: text().notNull().default('RIGHT'), // Always write right unless writing comments on the deleted lines
    severity: text().notNull(), // To tell the severity of the line changed/deleted ('critical', 'warning', 'suggestion')
    category: text().notNull(), // To tell which category this review falls on ('security', 'performance' etc.)
    body: text().notNull(), // The actual inline comment
    github_comment_id: bigint({ mode: "number" }), // The id assigned by Github after the inline comment is posted
    created_at: timestamp().notNull().defaultNow()
})

// ─── jobs ─────────────────────────────────────────────────────────────────────
// Mirror of BullMQ job state in Postgres.
// BullMQ state lives in Redis, which is ephemeral and hard to query.
// This table makes job state durable, queryable, and visible in the dashboard.
export const jobs = pgTable("jobs", {
    id: uuid().primaryKey().defaultRandom(),
    bull_job_id: text().unique().notNull(), // The job id assigned by the bullMQ
    review_id: uuid().references(() => reviews.id, { onDelete: "cascade" }).notNull(),
    status: text().notNull().default('waiting'), // Status of the bullMQ original state ('waiting', 'active', 'completed' etc.) updated by the worker on transaction
    attempts: integer().notNull().default(0),
    max_attempts: integer().notNull().default(3),
    failed_reason: text(), // If status is failed, the last error message
    created_at: timestamp().notNull().defaultNow(),
    updated_at: timestamp().notNull().defaultNow()
})

